---
title: 'Case Study: Modularizing a Package'
author: Laura Bakala
date: 2022-08-04
slug: case-study-modularizing-a-package
categories: []
tags: []
description: ""
output:
  blogdown::html_page:
    toc: true
---

"Would it be possible…?", "I think it would be nice if…", "Can you implement…?".

User feedback is a reliable source of valuable ideas for package improvement, but it's easy to get too eager and implement everything the users want, especially when you've only started making a name for yourself. Me and Dominik have fallen victim to that too.

## Origins of deepdep

Our package [deepdep](https://github.com/DominikRafacz/deepdep) was initially created as a university project. The teacher had a use case in mind (creating layered dependency plots) and we wanted to implement all that could get us a good grade. So we added everything more or less related to dependency plots that we could implement at the time.

Fast forward a few years and a question came up regarding using repository mirror other than the CRAN mirror we hardcoded. The function in question? `get_available_packages()`. We've exchanged a few messages and it turned out that `get_available_packages()` only served as a safeguard against using other mirrors within `deepdep()` itself.

In fact, the whole backend that downloads the data needed a rewrite. `get_dependencies()` tried to provide a unified API for retrieving dependencies from different sources and `get_descriptions()` did the same for DESCRIPTION... but they ended messy and counterintuitive. The user could only get data from CRAN, CRAN and Bioconductor, or from the local library that was first in `.localPaths()`. No handling Bioconductor only, no using CRAN as a fallback for local library, no querying other repositories (e.g. R-universe). The functions had to grow a lot if we wanted them to be as universal as possible.

The other issue made us realize that the plotting feature is optional to some; that the key feature is collecting dependency data in a table, which only needs a small fraction of dependencies ([httr](https://github.com/r-lib/httr) and [jsonlite](https://github.com/jeroen/jsonlite)). We moved a lot of previous Imports to Suggests ([ggplot2](https://github.com/tidyverse/ggplot2), [ggraph](https://github.com/thomasp85/ggraph), [graphlayouts](https://github.com/schochastics/graphlayouts), [igraph](https://github.com/igraph/rigraph), and [scales](https://github.com/r-lib/scales)), lightening deepdep significantly... but that's a topic for another post.

It was time to ask ourselves: "what does «deepdep» mean to us?". The answer was: "it's a package that helps with analyzing and vizualizing hierarchy of package dependencies". No more, no less. The functions that extracted dependencies of a package or a DESCRIPTION file were just tools to accomplish that goal. They were exported because "we couldn't let a good function go to waste", not because they presented a functionality we wanted to provide. If a user would want to use one of these, they'd have to install the whole deepdep; it would be like installing ggplot2 for `cut_interval()` and `cut_width()` instead of plotting.

The time has come for a separation.

## Separation of woodendesc





## Modularization of tidysq

<!-- (sth about tidysq and tidysqfiles and removing sq_encode()) -->
